### ISSUE TITLE
.iml files not found

### ISSUE THREAD

**Issue by Biscottex** [Kenny959/Vinyl#1]
Vinyl.iml is not found.
Impossible to start the project with Android Studio on Linux.

**Comment by Kenny959** [comment]
Ah bon? 

On Check çà demain ;-)

Kenny Vanmeenen

**Comment by Kenny959** [comment]
.iml files added to repo.
Should work now!

Please pull the latest code from this repo and retry.
then we could close the ticket.

if not, let us know,
K.

**Comment by Kenny959** [comment]
Hi Biscottex,

Is your issue solved now?

Please let me know If / when you need help.

K.
